[package]
name = "smooth_blue"
version = "0.1.0"
authors = ["James Munns <james.munns@gmail.com>"]
publish = false
build = "build.rs"

[dependencies]
cortex-m = "0.1.6"
r0 = "0.2.0"

[dependencies.compiler_builtins]
features = ["mem"]
git = "https://github.com/rust-lang-nursery/compiler-builtins"

[build-dependencies]
bindgen = {git = "https://github.com/servo/rust-bindgen", rev = "master"}
glob = "*"
# bindgen = { path = "../rust-bindgen" }
# gcc = "0.3"

# [features]
# testing_only_llvm_stable = ["bindgen/testing_only_llvm_stable"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true